AllCops:
  TargetRubyVersion: 2.7

require:
  - rubocop-performance


Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/WordArray:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantSelf:
  Enabled: false
